framework:
    router:
        # Used for CLI and absolute URL generation (Docker: DEFAULT_URI=http://localhost)
        default_uri: '%env(DEFAULT_URI)%'

when@prod:
    framework:
        router:
            strict_requirements: null
